[pytest]
DJANGO_SETTINGS_MODULE = tribel_scholar.settings
python_files = tests.py test_*.py *_tests.py
addopts = --disable-warnings -v --reuse-db
pythonpath = . apps
markers =
    requires_postgresql: mark test as requiring a live PostgreSQL database (skipped on SQLite)
