# Generated by Django 5.1.15 on 2026-10-03 16:24

import django.db.models.deletion
import uuid
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('applications', '0008_alter_applicationfieldvalue_source'),
        ('notifications', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='OTPVerification',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('phone_number', models.CharField(db_index=True, max_length=15)),
                ('phone_masked', models.CharField(max_length=20)),
                ('otp_hash', models.CharField(max_length=255)),
                ('attempts', models.PositiveIntegerField(default=0)),
                ('max_attempts', models.PositiveIntegerField(default=5)),
                ('expires_at', models.DateTimeField()),
                ('is_verified', models.BooleanField(default=False)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('user', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='otp_verifications', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'ordering': ['-created_at'],
                'indexes': [models.Index(fields=['phone_number', 'is_verified', 'expires_at'], name='notificatio_phone_n_a39779_idx')],
            },
        ),
        migrations.CreateModel(
            name='SMSNotification',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('notification_type', models.CharField(choices=[('APPLICATION_SUBMITTED', 'Application Submitted'), ('VERIFICATION_COMPLETED', 'Verification Completed'), ('NEEDS_MORE_EVIDENCE', 'Action Required / Needs More Evidence'), ('APPLICATION_STATUS_CHANGED', 'Application Status Changed'), ('DOCUMENT_PROCESSING_COMPLETED', 'Document Processing Completed'), ('OTP', 'One-Time Password')], db_index=True, max_length=50)),
                ('recipient_phone_masked', models.CharField(help_text='Masked phone number (e.g. ******4912) to protect PII.', max_length=20)),
                ('provider', models.CharField(default='fast2sms', max_length=50)),
                ('provider_request_id', models.CharField(blank=True, max_length=150, null=True)),
                ('status', models.CharField(choices=[('PENDING', 'Pending Dispatch'), ('SENDING', 'Sending via Provider'), ('SENT', 'Delivered to Provider'), ('FAILED', 'Delivery Failed'), ('RETRY_PENDING', 'Pending Retry'), ('DEV_SKIPPED', 'Skipped in Development Mode')], db_index=True, default='PENDING', max_length=30)),
                ('message_length', models.PositiveIntegerField(default=0)),
                ('idempotency_key', models.CharField(db_index=True, help_text='Unique key ensuring idempotency and zero duplicate SMS transmissions.', max_length=255, unique=True)),
                ('failure_reason', models.TextField(blank=True, default='')),
                ('retry_count', models.PositiveIntegerField(default=0)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('sent_at', models.DateTimeField(blank=True, null=True)),
                ('application', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='sms_notifications', to='applications.application')),
                ('recipient_user', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='sms_notifications', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'ordering': ['-created_at'],
                'indexes': [models.Index(fields=['application', 'notification_type'], name='notificatio_applica_7ec3fa_idx'), models.Index(fields=['status', 'created_at'], name='notificatio_status_a95ea7_idx')],
            },
        ),
    ]
