# Generated by Django 5.1.15 on 2026-10-03 16:49

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('notifications', '0002_otpverification_smsnotification'),
    ]

    operations = [
        migrations.AddField(
            model_name='smsnotification',
            name='delivered_at',
            field=models.DateTimeField(blank=True, help_text='Timestamp when carrier confirmed delivery via future DLR webhook.', null=True),
        ),
        migrations.AddField(
            model_name='smsnotification',
            name='dlr_payload_json',
            field=models.JSONField(blank=True, default=dict, help_text='Raw delivery report webhook payload for audit.'),
        ),
        migrations.AddField(
            model_name='smsnotification',
            name='dlr_status',
            field=models.CharField(blank=True, default='', help_text='Carrier delivery receipt status.', max_length=50),
        ),
        migrations.AlterField(
            model_name='smsnotification',
            name='sent_at',
            field=models.DateTimeField(blank=True, help_text='Timestamp when provider accepted the SMS.', null=True),
        ),
        migrations.AlterField(
            model_name='smsnotification',
            name='status',
            field=models.CharField(choices=[('PENDING', 'Pending Dispatch'), ('SENDING', 'Sending via Provider'), ('SENT_TO_PROVIDER', 'Dispatched / Sent to Provider'), ('DELIVERED', 'Delivered to Recipient (DLR Confirmed)'), ('FAILED', 'Delivery Failed'), ('RETRY_PENDING', 'Pending Retry'), ('DEV_SKIPPED', 'Skipped in Development Mode')], db_index=True, default='PENDING', max_length=30),
        ),
    ]
