# Generated by Django 5.1.15 on 2026-09-27 16:11

import apps.core.validators
import django.db.models.deletion
import uuid
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('documents', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='ReferenceSet',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('code', models.CharField(help_text='Unique identifier (e.g., TOP_CLASS_PREMIER_INSTITUTES)', max_length=100, unique=True)),
                ('name', models.CharField(max_length=255)),
                ('description', models.TextField(blank=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
            options={
                'ordering': ['code'],
            },
        ),
        migrations.CreateModel(
            name='Scheme',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('code', models.CharField(help_text='Unique scheme code (e.g. NFST, NOS, TOP_CLASS)', max_length=50, unique=True)),
                ('name', models.CharField(help_text='Official name of the scholarship/fellowship', max_length=255)),
                ('description', models.TextField(help_text='Detailed objective and scope')),
                ('ministry', models.CharField(default='Ministry of Tribal Affairs', max_length=150)),
                ('scheme_type', models.CharField(choices=[('FELLOWSHIP', 'Higher Education Fellowship'), ('SCHOLARSHIP', 'National Scholarship'), ('OVERSEAS', 'Overseas Scholarship/Fellowship')], default='SCHOLARSHIP', max_length=50)),
                ('active', models.BooleanField(default=True, help_text='Master active switch for the scheme')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
            options={
                'ordering': ['code'],
            },
        ),
        migrations.CreateModel(
            name='SchemeVersion',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('academic_year', models.CharField(help_text='Academic year formatted as YYYY-YY (e.g., 2025-26)', max_length=20, validators=[apps.core.validators.validate_academic_year])),
                ('version_number', models.PositiveIntegerField(default=1, help_text='Sequential version within the academic year')),
                ('status', models.CharField(choices=[('DRAFT', 'Draft / Under Revision'), ('APPROVED', 'Officially Approved'), ('ACTIVE', 'Active for Applications'), ('ARCHIVED', 'Archived / Concluded'), ('SUPERSEDED', 'Superseded by Newer Version')], default='DRAFT', max_length=30)),
                ('effective_from', models.DateField(blank=True, null=True)),
                ('effective_to', models.DateField(blank=True, null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('approved_at', models.DateTimeField(blank=True, null=True)),
                ('scheme', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='versions', to='schemes.scheme')),
                ('source_document', models.ForeignKey(help_text='Official guideline, notification or advertisement authorizing this scheme version', on_delete=django.db.models.deletion.PROTECT, related_name='scheme_versions', to='documents.sourcedocument')),
            ],
            options={
                'ordering': ['scheme', '-academic_year', '-version_number'],
                'unique_together': {('scheme', 'academic_year', 'version_number')},
            },
        ),
        migrations.CreateModel(
            name='ReferenceSetItem',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('external_code', models.CharField(help_text='External identifier such as AISHE code, NIRF rank or institute code', max_length=100)),
                ('name', models.CharField(help_text='Full institution name, course title or item label', max_length=255)),
                ('metadata_json', models.JSONField(blank=True, default=dict, help_text='Structured attributes (e.g., state, institute category, nirf_rank)')),
                ('valid_from', models.DateField(blank=True, null=True)),
                ('valid_to', models.DateField(blank=True, null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('reference_set', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='items', to='schemes.referenceset')),
                ('source_document', models.ForeignKey(help_text='Official document or gazette list proving provenance of this item', on_delete=django.db.models.deletion.PROTECT, related_name='reference_set_items', to='documents.sourcedocument')),
            ],
            options={
                'ordering': ['reference_set', 'name'],
                'unique_together': {('reference_set', 'external_code')},
            },
        ),
        migrations.CreateModel(
            name='SchemeRule',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('rule_code', models.CharField(help_text='Unique rule identifier (e.g. NFST_ST_BENEFICIARY)', max_length=100)),
                ('rule_type', models.CharField(choices=[('ELIGIBILITY', 'Mandatory Eligibility Rule'), ('PREFERENCE', 'Preference / Prioritization Metric'), ('RESTRICTION', 'Exclusion / Ineligibility Restriction'), ('QUOTA', 'Slot Allocation / Quota'), ('DOCUMENT_REQUIREMENT', 'Documentary Evidence Requirement')], default='ELIGIBILITY', max_length=30)),
                ('field_path', models.CharField(help_text="Application data path, e.g. 'applicant.community' or 'applicant.annual_family_income'", max_length=255)),
                ('operator', models.CharField(choices=[('EQUALS', 'Equals (==)'), ('NOT_EQUALS', 'Not Equals (!=)'), ('LESS_THAN_OR_EQUAL', 'Less Than or Equal (<=)'), ('GREATER_THAN_OR_EQUAL', 'Greater Than or Equal (>=)'), ('IN_SET', 'In Set / In Reference Set'), ('NOT_IN_SET', 'Not In Set'), ('EXISTS', 'Field Exists and Non-Empty'), ('PENDING_OFFICIAL_EXTRACTION', 'Pending Official Extraction')], max_length=40)),
                ('value', models.JSONField(blank=True, help_text="Expected scalar/list value (e.g. 'ST', 600000). Null if PENDING_OFFICIAL_EXTRACTION.", null=True)),
                ('failure_message', models.TextField(help_text='Human-readable citation displayed upon failure')),
                ('severity', models.CharField(choices=[('BLOCKING', 'Blocking (Ineligible if Failed)'), ('WARNING', 'Warning / Informational'), ('MANUAL_REVIEW', 'Requires Human Officer Review')], default='BLOCKING', max_length=30)),
                ('requires_human_review', models.BooleanField(default=False, help_text='True if ambiguous/failed evaluation requires human officer scrutiny')),
                ('status', models.CharField(choices=[('ACTIVE', 'Active'), ('DRAFT', 'Draft'), ('PENDING_OFFICIAL_SOURCE_EXTRACTION', 'Pending Official Source Extraction')], default='ACTIVE', help_text='Active or pending official gazette extraction', max_length=50)),
                ('reference_set', models.ForeignKey(blank=True, help_text='Reference set for IN_SET checks (e.g. list of premier institutes)', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='rules', to='schemes.referenceset')),
                ('source_document', models.ForeignKey(help_text='Exact source document proving legal provenance for this rule', on_delete=django.db.models.deletion.PROTECT, related_name='rules', to='documents.sourcedocument')),
                ('scheme_version', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='rules', to='schemes.schemeversion')),
            ],
            options={
                'ordering': ['scheme_version', 'rule_code'],
                'unique_together': {('scheme_version', 'rule_code')},
            },
        ),
    ]
