# Generated by Django 5.1.15 on 2026-09-27 16:16

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('documents', '0002_initial'),
        ('schemes', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='referencesetitem',
            name='source_document',
            field=models.ForeignKey(blank=True, help_text='Official document or gazette list proving provenance of this item', null=True, on_delete=django.db.models.deletion.PROTECT, related_name='reference_set_items', to='documents.sourcedocument'),
        ),
        migrations.AlterField(
            model_name='schemerule',
            name='source_document',
            field=models.ForeignKey(blank=True, help_text='Exact source document proving legal provenance for this rule', null=True, on_delete=django.db.models.deletion.PROTECT, related_name='rules', to='documents.sourcedocument'),
        ),
    ]
