# Generated by Django 5.1.15 on 2026-09-27 16:52

import django.db.models.deletion
import uuid
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('documents', '0002_initial'),
        ('schemes', '0002_alter_referencesetitem_source_document_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='schemerule',
            name='rule_type',
        ),
        migrations.AddField(
            model_name='referenceset',
            name='coverage_percentage',
            field=models.FloatField(default=0.0, help_text='Coverage percentage: (loaded / expected) * 100'),
        ),
        migrations.AddField(
            model_name='referenceset',
            name='dataset_status',
            field=models.CharField(choices=[('SAMPLE', 'Representative Sample (Incomplete)'), ('PARTIAL', 'Partial Dataset (Work In Progress)'), ('COMPLETE', 'Complete Official Roster'), ('VERIFIED', 'Complete and Cryptographically Verified')], default='SAMPLE', help_text='Completeness status of master dataset', max_length=30),
        ),
        migrations.AddField(
            model_name='referenceset',
            name='record_count_expected',
            field=models.PositiveIntegerField(default=0, help_text='Total expected records from official publication (e.g. 265 for Top Class)'),
        ),
        migrations.AddField(
            model_name='referenceset',
            name='record_count_loaded',
            field=models.PositiveIntegerField(default=0, help_text='Current loaded record count in this reference set'),
        ),
        migrations.AddField(
            model_name='referenceset',
            name='source_document',
            field=models.ForeignKey(blank=True, help_text='Official source publication authorizing this master dataset', null=True, on_delete=django.db.models.deletion.PROTECT, related_name='reference_sets', to='documents.sourcedocument'),
        ),
        migrations.AddField(
            model_name='referenceset',
            name='verified_at',
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='schemerule',
            name='category',
            field=models.CharField(choices=[('ELIGIBILITY', 'Eligibility (Objective Binary Qualification)'), ('DOCUMENT', 'Document Requirement'), ('SELECTION', 'Selection / Merit Scoring'), ('PREFERENCE', 'Preference / Prioritization Metric'), ('QUOTA', 'Quota / Capacity Allocation'), ('BENEFIT', 'Benefit / Entitlement Structure'), ('WORKFLOW', 'Workflow / Statutory Transition'), ('VALIDATION', 'System / Data Integrity Validation')], default='ELIGIBILITY', help_text='Explicit functional category of this scheme rule', max_length=30),
        ),
        migrations.AddField(
            model_name='schemerule',
            name='confidence',
            field=models.CharField(default='OFFICIAL', max_length=30),
        ),
        migrations.AddField(
            model_name='schemerule',
            name='preference_type',
            field=models.CharField(blank=True, default='PRIORITY', help_text='For PREFERENCE rules: PRIORITY, RESERVATION, TIE_BREAKER', max_length=50),
        ),
        migrations.AddField(
            model_name='schemerule',
            name='source_excerpt',
            field=models.TextField(blank=True, help_text='Short exact excerpt from the official publication justifying this rule'),
        ),
        migrations.AlterField(
            model_name='referenceset',
            name='code',
            field=models.CharField(help_text='Unique identifier (e.g., TOP_CLASS_PREMIER_INSTITUTES_SAMPLE)', max_length=100, unique=True),
        ),
        migrations.AlterField(
            model_name='schemerule',
            name='rule_code',
            field=models.CharField(help_text='Unique rule identifier (e.g. NFST_2025_ST_COMMUNITY)', max_length=100),
        ),
        migrations.CreateModel(
            name='InstitutionEligibility',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('course_name', models.CharField(help_text='Specific course, e.g., B.Tech, MBBS, MBA, LL.B, B.Des', max_length=255)),
                ('course_code', models.CharField(blank=True, help_text='Standard discipline/course code if available', max_length=100)),
                ('eligibility_status', models.CharField(choices=[('ELIGIBLE', 'Eligible Course in this Institution'), ('INELIGIBLE', 'Ineligible Course'), ('CONDITIONAL', 'Conditional / Subject to Special Approval')], default='ELIGIBLE', max_length=30)),
                ('valid_from', models.DateField(blank=True, null=True)),
                ('valid_to', models.DateField(blank=True, null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('institution', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='course_eligibilities', to='schemes.referencesetitem')),
                ('scheme_version', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='institution_eligibilities', to='schemes.schemeversion')),
                ('source_document', models.ForeignKey(help_text='Official roster proving course-specific eligibility', on_delete=django.db.models.deletion.PROTECT, related_name='institution_eligibilities', to='documents.sourcedocument')),
            ],
            options={
                'ordering': ['institution', 'course_name'],
                'unique_together': {('scheme_version', 'institution', 'course_name')},
            },
        ),
        migrations.CreateModel(
            name='SchemeQuota',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('quota_code', models.CharField(help_text='e.g. NFST_2025_TOTAL_SLOTS, NOS_2025_PVTG_AWARDS', max_length=100)),
                ('total_capacity', models.PositiveIntegerField(help_text='Total allocation capacity (e.g., 750 for NFST, 20 for NOS)')),
                ('category', models.CharField(default='ST', help_text='Target category: ST, PVTG, ALL', max_length=50)),
                ('gender', models.CharField(choices=[('ANY', 'Any Gender'), ('FEMALE', 'Female Only (Earmarked)'), ('MALE', 'Male')], default='ANY', max_length=30)),
                ('preference_group', models.CharField(blank=True, help_text='Sub-group: DIVYANGJAN, PVTG, NONE', max_length=50)),
                ('reserved_capacity', models.PositiveIntegerField(default=0, help_text='Earmarked / reserved slots within total capacity')),
                ('effective_from', models.DateField(blank=True, null=True)),
                ('effective_to', models.DateField(blank=True, null=True)),
                ('status', models.CharField(default='ACTIVE', max_length=30)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('scheme_version', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='quotas', to='schemes.schemeversion')),
                ('source_document', models.ForeignKey(help_text='Official publication defining this quota', on_delete=django.db.models.deletion.PROTECT, related_name='quotas', to='documents.sourcedocument')),
            ],
            options={
                'ordering': ['scheme_version', 'quota_code'],
                'unique_together': {('scheme_version', 'quota_code')},
            },
        ),
        migrations.CreateModel(
            name='SelectionMethod',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('code', models.CharField(help_text='e.g. EXPERT_COMMITTEE_INTERVIEW, UGC_NET_MERIT_SCORE', max_length=100)),
                ('name', models.CharField(max_length=255)),
                ('human_decision_required', models.BooleanField(default=True, help_text='Whether selection requires human expert/committee sign-off')),
                ('description', models.TextField(help_text='Detailed description of selection procedure')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('scheme_version', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='selection_methods', to='schemes.schemeversion')),
                ('source_document', models.ForeignKey(help_text='Official publication authorizing this selection method', on_delete=django.db.models.deletion.PROTECT, related_name='selection_methods', to='documents.sourcedocument')),
            ],
            options={
                'ordering': ['scheme_version', 'code'],
                'unique_together': {('scheme_version', 'code')},
            },
        ),
    ]
