# Generated by Django 5.1.15 on 2026-09-28 04:06

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('schemes', '0004_schemerule_provenance_status'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='schemerule',
            name='provenance_status',
        ),
    ]
