# Generated by Django 5.1.15 on 2026-09-28 04:12

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('schemes', '0005_remove_schemerule_provenance_status'),
    ]

    operations = [
        migrations.AddField(
            model_name='schemerule',
            name='provenance_status',
            field=models.CharField(choices=[('OFFICIAL_VERIFIED', 'Official Verified'), ('OFFICIAL_PENDING_VERIFICATION', 'Official Pending Verification'), ('UNVERIFIED', 'Unverified')], default='OFFICIAL_VERIFIED', help_text='Status of legal/official provenance for this rule', max_length=40),
        ),
    ]
