# Generated by Django 5.1.15 on 2026-09-28 04:38

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('schemes', '0006_schemerule_provenance_status'),
    ]

    operations = [
        migrations.AddField(
            model_name='schemerule',
            name='superseded_at',
            field=models.DateTimeField(blank=True, help_text='Timestamp when this rule was superseded or retired', null=True),
        ),
        migrations.AddField(
            model_name='schemerule',
            name='superseded_by_rule',
            field=models.ForeignKey(blank=True, help_text='Replacement rule that supersedes this historical rule', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='superseded_rules', to='schemes.schemerule'),
        ),
        migrations.AddField(
            model_name='schemerule',
            name='superseded_reason',
            field=models.TextField(blank=True, help_text='Statutory explanation or amendment citation for superseding this rule'),
        ),
        migrations.AlterField(
            model_name='schemerule',
            name='status',
            field=models.CharField(choices=[('DRAFT', 'Draft'), ('ACTIVE', 'Active'), ('SUSPENDED', 'Suspended'), ('SUPERSEDED', 'Superseded'), ('RETIRED', 'Retired'), ('PENDING_OFFICIAL_SOURCE_EXTRACTION', 'Pending Official Source Extraction')], default='ACTIVE', help_text='Lifecycle status of rule: DRAFT, ACTIVE, SUSPENDED, SUPERSEDED, RETIRED', max_length=50),
        ),
    ]
