# Generated by Django 5.1.15 on 2026-09-28 17:41

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('schemes', '0007_schemerule_superseded_at_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='schemerule',
            name='provenance_status',
            field=models.CharField(choices=[('OFFICIAL_VERIFIED', 'Official Verified'), ('OFFICIAL_PENDING_VERIFICATION', 'Official Pending Verification'), ('UNVERIFIED', 'Unverified'), ('UNSUPPORTED', 'Unsupported by official sources')], default='OFFICIAL_VERIFIED', help_text='Status of legal/official provenance for this rule', max_length=40),
        ),
    ]
