# Generated by Django 5.1.15 on 2026-09-27 16:11

import django.db.models.deletion
import uuid
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('applications', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='VerificationQueueItem',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('item_type', models.CharField(choices=[('DOCUMENT', 'Document OCR & Integrity'), ('RULE_EVALUATION', 'Rule / Criteria Evaluation'), ('IDENTITY', 'Identity / Demographics Match'), ('INSTITUTE', 'Institute / Course Eligibility')], max_length=40)),
                ('target_identifier', models.CharField(help_text='Rule code or document reference', max_length=150)),
                ('confidence_score', models.FloatField(default=1.0, help_text='Confidence output from AI OCR or extraction (0.0 - 1.0)')),
                ('status', models.CharField(choices=[('PENDING', 'Pending Human Review'), ('APPROVED', 'Officer Verified & Approved'), ('DEFECT_FLAGGED', 'Defect Identified (Sent back to Applicant)'), ('REJECTED', 'Officer Rejected')], default='PENDING', max_length=30)),
                ('ai_assistance_json', models.JSONField(blank=True, default=dict, help_text='Extracted text snippets, bounding boxes, or anomaly explanations from AI')),
                ('officer_remarks', models.TextField(blank=True, help_text='Statutory notes entered by verifying officer')),
                ('reviewed_at', models.DateTimeField(blank=True, null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('application', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='verification_items', to='applications.application')),
                ('reviewed_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='verifications_performed', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'ordering': ['status', 'created_at'],
            },
        ),
    ]
