# Generated by Django 5.1.15 on 2026-09-29 21:00

import django.db.models.deletion
import django.utils.timezone
import uuid
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('applications', '0007_application_last_modified_at_and_more'),
        ('documents', '0007_ocrpage_ocrjob_ocrblock_ocrresult_ocrpage_ocr_result_and_more'),
        ('verification', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='DocumentVerificationRecord',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('field_code', models.CharField(db_index=True, max_length=100)),
                ('previous_value_json', models.JSONField(blank=True, null=True)),
                ('verified_value_json', models.JSONField(blank=True, null=True)),
                ('verification_status', models.CharField(choices=[('PENDING', 'Pending Human Review'), ('VERIFIED', 'Explicitly Verified by Officer'), ('REJECTED', 'Explicitly Rejected by Officer'), ('CONFLICT', 'Material Field Conflict Flagged'), ('NEEDS_REVIEW', 'Requires Additional Review / Inquiry')], default='PENDING', max_length=30)),
                ('decision_action', models.CharField(choices=[('USE_APPLICANT_DECLARATION', 'Use Applicant Declaration'), ('USE_DOCUMENT_VALUE', 'Use Document Evidence Value'), ('REQUEST_CORRECTION', 'Request Correction from Applicant'), ('NEEDS_REVIEW', 'Flag for Senior Review'), ('NO_CONFLICT', 'Direct Field Verification (No Conflict)')], default='NO_CONFLICT', max_length=40)),
                ('officer_role', models.CharField(blank=True, max_length=50)),
                ('verified_at', models.DateTimeField(default=django.utils.timezone.now)),
                ('reason', models.TextField(blank=True)),
                ('verification_method', models.CharField(choices=[('MANUAL_REVIEW', 'Manual Officer Inspection'), ('CONFLICT_RESOLUTION', 'Conflict Resolution Workflow'), ('DOCUMENT_EVIDENCE', 'Document Evidence Verification'), ('REOPENED', 'Verification Reopened')], default='MANUAL_REVIEW', max_length=50)),
                ('is_current', models.BooleanField(db_index=True, default=True)),
                ('correlation_id', models.CharField(blank=True, db_index=True, max_length=100)),
                ('document', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='verification_records', to='documents.applicantdocument')),
                ('document_version', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='verification_records', to='documents.documentversion')),
                ('field_definition', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='verification_records', to='applications.applicationfielddefinition')),
                ('ocr_block', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='verification_records', to='documents.ocrblock')),
                ('ocr_page', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='verification_records', to='documents.ocrpage')),
                ('ocr_result', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='verification_records', to='documents.ocrresult')),
                ('officer', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='officer_verification_records', to=settings.AUTH_USER_MODEL)),
                ('superseded_record', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='superseding_records', to='verification.documentverificationrecord')),
            ],
            options={
                'ordering': ['-verified_at'],
                'indexes': [models.Index(fields=['document', 'field_code', 'is_current'], name='verificatio_documen_cb6677_idx'), models.Index(fields=['verification_status'], name='verificatio_verific_ac5c4c_idx'), models.Index(fields=['officer'], name='verificatio_officer_4a0375_idx')],
            },
        ),
    ]
