# Generated by Django 5.1.15 on 2026-10-02 18:48

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('applications', '0008_alter_applicationfieldvalue_source'),
        ('documents', '0007_ocrpage_ocrjob_ocrblock_ocrresult_ocrpage_ocr_result_and_more'),
        ('verification', '0002_documentverificationrecord'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='verificationqueueitem',
            options={'ordering': ['priority', 'status', 'created_at']},
        ),
        migrations.AddField(
            model_name='documentverificationrecord',
            name='audit_event_id',
            field=models.CharField(blank=True, db_index=True, default='', max_length=100),
        ),
        migrations.AddField(
            model_name='documentverificationrecord',
            name='previous_source',
            field=models.CharField(blank=True, default='', help_text='e.g. APPLICANT_DECLARED, OCR_PROVISIONAL', max_length=50),
        ),
        migrations.AddField(
            model_name='documentverificationrecord',
            name='previous_trust_rank',
            field=models.IntegerField(default=10),
        ),
        migrations.AddField(
            model_name='documentverificationrecord',
            name='verified_source',
            field=models.CharField(default='OFFICER_VERIFIED', help_text='e.g. OFFICER_VERIFIED, VERIFIED_DOCUMENT', max_length=50),
        ),
        migrations.AddField(
            model_name='documentverificationrecord',
            name='verified_trust_rank',
            field=models.IntegerField(default=60),
        ),
        migrations.AddField(
            model_name='verificationqueueitem',
            name='assigned_at',
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='verificationqueueitem',
            name='assigned_to',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='assigned_verification_items', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='verificationqueueitem',
            name='conflict_type',
            field=models.CharField(blank=True, db_index=True, default='', help_text='e.g. MATERIAL_CONFLICT, DATA_MISMATCH, UNREADABLE_SCAN', max_length=50),
        ),
        migrations.AddField(
            model_name='verificationqueueitem',
            name='current_evidence_json',
            field=models.JSONField(blank=True, default=dict, help_text='Snapshot of declared vs OCR vs official values and respective trust ranks'),
        ),
        migrations.AddField(
            model_name='verificationqueueitem',
            name='document',
            field=models.ForeignKey(blank=True, help_text='Direct link to supporting applicant document under scrutiny', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='verification_items', to='documents.applicantdocument'),
        ),
        migrations.AddField(
            model_name='verificationqueueitem',
            name='priority',
            field=models.CharField(choices=[('LOW', 'Low'), ('NORMAL', 'Normal'), ('HIGH', 'High'), ('URGENT', 'Urgent')], db_index=True, default='NORMAL', max_length=20),
        ),
        migrations.AlterField(
            model_name='documentverificationrecord',
            name='decision_action',
            field=models.CharField(choices=[('USE_APPLICANT_DECLARATION', 'Use Applicant Declaration'), ('USE_DOCUMENT_VALUE', 'Use Document Evidence Value'), ('REQUEST_CORRECTION', 'Request Correction from Applicant'), ('NEEDS_MORE_EVIDENCE', 'Needs More Evidence'), ('ESCALATE', 'Escalate to Senior Officer'), ('NEEDS_REVIEW', 'Flag for Senior Review'), ('NO_CONFLICT', 'Direct Field Verification (No Conflict)'), ('VERIFIED_DOCUMENT', 'Verified Supporting Document Evidence')], default='NO_CONFLICT', max_length=40),
        ),
        migrations.AlterField(
            model_name='verificationqueueitem',
            name='status',
            field=models.CharField(choices=[('PENDING', 'Pending Human Review'), ('IN_REVIEW', 'Under Officer Review'), ('VERIFIED', 'Officer Verified'), ('REJECTED', 'Officer Rejected'), ('NEEDS_MORE_EVIDENCE', 'Needs More Evidence'), ('ESCALATED', 'Escalated to Senior Authority'), ('CLOSED', 'Closed'), ('APPROVED', 'Officer Verified & Approved'), ('DEFECT_FLAGGED', 'Defect Identified')], db_index=True, default='PENDING', max_length=30),
        ),
        migrations.AddIndex(
            model_name='verificationqueueitem',
            index=models.Index(fields=['status', 'priority'], name='verificatio_status_6a30d2_idx'),
        ),
        migrations.AddIndex(
            model_name='verificationqueueitem',
            index=models.Index(fields=['assigned_to', 'status'], name='verificatio_assigne_f390fc_idx'),
        ),
        migrations.AddIndex(
            model_name='verificationqueueitem',
            index=models.Index(fields=['conflict_type'], name='verificatio_conflic_06ecbe_idx'),
        ),
    ]
