# Generated by Django 5.1.15 on 2026-09-27 16:11

import django.db.models.deletion
import uuid
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='AuditLog',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('actor_role', models.CharField(blank=True, help_text='Role at time of action', max_length=50)),
                ('entity_type', models.CharField(help_text='Model class or domain aggregate (e.g. SchemeRule)', max_length=100)),
                ('entity_id', models.CharField(help_text='Primary key identifier of targeted entity', max_length=100)),
                ('action', models.CharField(choices=[('CREATE', 'Create Entity'), ('UPDATE', 'Update Entity'), ('DELETE', 'Delete Entity'), ('TRANSITION', 'Workflow Transition'), ('ACCESS', 'Sensitive Data Access'), ('VALIDATE', 'Rule / System Validation')], max_length=30)),
                ('before_json', models.JSONField(blank=True, help_text='State snapshot before mutation', null=True)),
                ('after_json', models.JSONField(blank=True, help_text='State snapshot after mutation', null=True)),
                ('reason', models.TextField(blank=True, help_text='Justification provided by actor')),
                ('ip_address', models.GenericIPAddressField(blank=True, help_text='Client IP address', null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('actor', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='audit_actions', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'ordering': ['-created_at'],
                'indexes': [models.Index(fields=['entity_type', 'entity_id'], name='audit_audit_entity__9535bf_idx'), models.Index(fields=['created_at'], name='audit_audit_created_2c1626_idx'), models.Index(fields=['actor'], name='audit_audit_actor_i_17b775_idx')],
            },
        ),
    ]
