# Generated by Django 5.1.15 on 2026-09-28 04:06

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('audit', '0002_alter_auditlog_action'),
    ]

    operations = [
        migrations.AlterField(
            model_name='auditlog',
            name='action',
            field=models.CharField(choices=[('CREATE', 'Create Entity'), ('UPDATE', 'Update Entity'), ('DELETE', 'Delete Entity'), ('TRANSITION', 'Workflow Transition'), ('ACCESS', 'Sensitive Data Access'), ('VALIDATE', 'Rule / System Validation')], max_length=30),
        ),
    ]
