# Generated by Django 5.1.15 on 2026-09-28 15:39

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('audit', '0005_alter_auditlog_action'),
    ]

    operations = [
        migrations.AlterField(
            model_name='auditlog',
            name='action',
            field=models.CharField(choices=[('CREATE', 'Create Entity'), ('UPDATE', 'Update Entity'), ('DELETE', 'Delete Entity'), ('TRANSITION', 'Workflow Transition'), ('ACCESS', 'Sensitive Data Access'), ('VALIDATE', 'Rule / System Validation'), ('ELIGIBILITY_EVALUATED', 'Eligibility Evaluated'), ('APPLICATION_CREATED', 'Application Created'), ('APPLICATION_SUBMITTED', 'Application Submitted'), ('SNAPSHOT_VIEWED', 'Sensitive Snapshot Viewed'), ('CONFLICT_DETECTED', 'Field Value Conflict Detected'), ('CONFLICT_RESOLVED', 'Field Value Conflict Resolved'), ('DUPLICATE_FLAGGED', 'Possible Duplicate Application Flagged'), ('FIELD_VALUE_CHANGED', 'Field Value Changed'), ('DOCUMENT_ADDED', 'Document Added'), ('DEFICIENCY_RAISED', 'Deficiency Raised'), ('DEFICIENCY_RESPONDED', 'Deficiency Responded'), ('DEFICIENCY_RESOLVED', 'Deficiency Resolved')], max_length=30),
        ),
    ]
