# Generated by Django 5.1.15 on 2026-09-27 16:11

import django.db.models.deletion
import uuid
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('applications', '0001_initial'),
        ('schemes', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='WorkflowDefinition',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('name', models.CharField(max_length=150)),
                ('active', models.BooleanField(default=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('scheme_version', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='workflow', to='schemes.schemeversion')),
            ],
        ),
        migrations.CreateModel(
            name='WorkflowState',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('code', models.CharField(help_text='Machine-readable code (e.g., DRAFT, UNDER_SCRUTINY, APPROVED)', max_length=50)),
                ('display_name', models.CharField(help_text='Human-friendly label', max_length=100)),
                ('sequence', models.PositiveIntegerField(help_text='Ordered sequence number for progression')),
                ('applicant_visible', models.BooleanField(default=True, help_text='Whether applicant can see this state')),
                ('officer_visible', models.BooleanField(default=True, help_text='Whether visible to verification officers')),
                ('terminal', models.BooleanField(default=False, help_text='Terminal states (e.g. APPROVED, REJECTED, DISBURSED)')),
                ('workflow', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='states', to='workflow.workflowdefinition')),
            ],
            options={
                'ordering': ['workflow', 'sequence'],
                'unique_together': {('workflow', 'code')},
            },
        ),
        migrations.CreateModel(
            name='ApplicationStatusHistory',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('reason', models.TextField(blank=True, help_text='Justification or official remarks for transition')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('application', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='status_history', to='applications.application')),
                ('changed_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, to=settings.AUTH_USER_MODEL)),
                ('from_state', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='+', to='workflow.workflowstate')),
                ('to_state', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='+', to='workflow.workflowstate')),
            ],
            options={
                'ordering': ['created_at'],
            },
        ),
        migrations.CreateModel(
            name='WorkflowTransition',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('required_role', models.CharField(help_text='Role authorized to trigger this transition (e.g., APPLICANT, SCRUTINY_OFFICER, ADMIN)', max_length=50)),
                ('requires_reason', models.BooleanField(default=False, help_text='Mandatory textual justification for this action (e.g. defect marking or rejection)')),
                ('rule_condition_json', models.JSONField(blank=True, default=dict, help_text='Pre-requisite criteria evaluated prior to allowing transition')),
                ('from_state', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='outgoing_transitions', to='workflow.workflowstate')),
                ('to_state', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='incoming_transitions', to='workflow.workflowstate')),
                ('workflow', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='transitions', to='workflow.workflowdefinition')),
            ],
            options={
                'ordering': ['workflow', 'from_state__sequence'],
                'unique_together': {('workflow', 'from_state', 'to_state', 'required_role')},
            },
        ),
    ]
