# Generated by Django 5.1.15 on 2026-09-27 16:11

import django.db.models.deletion
import uuid
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='ApplicantProfile',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('community', models.CharField(choices=[('ST', 'Scheduled Tribe'), ('PVTG', 'Particularly Vulnerable Tribal Group'), ('OTHER', 'Other (Non-ST)')], default='ST', max_length=20)),
                ('pvtg_group_name', models.CharField(blank=True, help_text='Specific PVTG group if applicable', max_length=150)),
                ('caste_certificate_number', models.CharField(blank=True, max_length=100)),
                ('caste_certificate_issuing_authority', models.CharField(blank=True, max_length=150)),
                ('annual_family_income', models.DecimalField(decimal_places=2, default=0.0, help_text='Gross annual parental/family income in INR', max_digits=12)),
                ('income_certificate_number', models.CharField(blank=True, max_length=100)),
                ('date_of_birth', models.DateField(blank=True, null=True)),
                ('gender', models.CharField(choices=[('FEMALE', 'Female'), ('MALE', 'Male'), ('OTHER', 'Other / Transgender')], default='FEMALE', max_length=20)),
                ('is_disabled', models.BooleanField(default=False)),
                ('disability_percentage', models.PositiveIntegerField(default=0)),
                ('udid_number', models.CharField(blank=True, max_length=100)),
                ('is_synthetic', models.BooleanField(default=True, help_text='Flag indicating synthetic / mock applicant for development and testing')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('user', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='applicant_profile', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'ordering': ['user__username'],
            },
        ),
    ]
