# Generated by Django 5.1.15 on 2026-09-27 16:11

import django.db.models.deletion
import uuid
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('applicants', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Application',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('application_number', models.CharField(help_text='Official tracking number (e.g. MOTA/2025-26/NFST/0001)', max_length=64, unique=True)),
                ('submission_data_json', models.JSONField(blank=True, default=dict, help_text='Canonical applicant submitted parameters evaluated against SchemeRules')),
                ('is_synthetic', models.BooleanField(default=True, help_text='True if this is a synthetic test dossier')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('applicant', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='applications', to='applicants.applicantprofile')),
            ],
            options={
                'ordering': ['-created_at'],
            },
        ),
    ]
