# Generated by Django 5.1.15 on 2026-09-27 16:11

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('applications', '0001_initial'),
        ('schemes', '0001_initial'),
        ('workflow', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='application',
            name='current_state',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='applications', to='workflow.workflowstate'),
        ),
        migrations.AddField(
            model_name='application',
            name='scheme_version',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='applications', to='schemes.schemeversion'),
        ),
        migrations.AddIndex(
            model_name='application',
            index=models.Index(fields=['application_number'], name='application_applica_423097_idx'),
        ),
        migrations.AddIndex(
            model_name='application',
            index=models.Index(fields=['scheme_version', 'current_state'], name='application_scheme__f554a3_idx'),
        ),
    ]
