# Generated by Django 5.1.15 on 2026-09-27 17:27

import django.db.models.deletion
import uuid
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('applications', '0002_initial'),
        ('schemes', '0004_schemerule_provenance_status'),
    ]

    operations = [
        migrations.CreateModel(
            name='EligibilityEvaluation',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('evaluated_at', models.DateTimeField(auto_now_add=True)),
                ('engine_version', models.CharField(default='1.0.0', max_length=50)),
                ('result', models.JSONField(default=dict, help_text='Standardized deterministic eligibility evaluation output dictionary')),
                ('result_hash', models.CharField(help_text='SHA-256 hash of canonical deterministic evaluation result', max_length=64)),
                ('application', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='eligibility_evaluations', to='applications.application')),
                ('scheme_version', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='evaluations', to='schemes.schemeversion')),
            ],
            options={
                'ordering': ['-evaluated_at'],
                'indexes': [models.Index(fields=['application', '-evaluated_at'], name='application_applica_6d07b5_idx'), models.Index(fields=['result_hash'], name='application_result__0bc96a_idx')],
            },
        ),
    ]
