# Generated by Django 5.1.15 on 2026-09-28 04:06

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('applications', '0003_eligibilityevaluation'),
    ]

    operations = [
        migrations.DeleteModel(
            name='EligibilityEvaluation',
        ),
    ]
