# Generated by Django 5.1.15 on 2026-09-28 04:38

import django.db.models.deletion
import uuid
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('applications', '0005_eligibilityevaluation'),
        ('documents', '0003_documentrequirement'),
        ('schemes', '0007_schemerule_superseded_at_and_more'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='ApplicationDeficiency',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('deficiency_code', models.CharField(help_text='Categorical code (e.g. DEF_INCOME_CERT_EXPIRED)', max_length=100)),
                ('field_code', models.CharField(blank=True, max_length=100)),
                ('document_type', models.CharField(blank=True, max_length=50)),
                ('description', models.TextField(help_text='Clear explanation of deficiency and remedy required')),
                ('severity', models.CharField(choices=[('BLOCKING', 'Blocking Deficiency'), ('WARNING', 'Warning / Informational'), ('CORRECTIVE', 'Corrective Resubmission Required')], default='BLOCKING', max_length=30)),
                ('raised_at', models.DateTimeField(auto_now_add=True)),
                ('due_at', models.DateTimeField(blank=True, null=True)),
                ('status', models.CharField(choices=[('OPEN', 'Open'), ('RESPONDED', 'Responded by Applicant'), ('UNDER_REVIEW', 'Under Review by Scrutiny Officer'), ('RESOLVED', 'Resolved by Officer'), ('WAIVED', 'Waived by Officer')], default='OPEN', max_length=30)),
                ('resolution_text', models.TextField(blank=True, help_text='Applicant explanation or officer resolution justification')),
                ('resolved_at', models.DateTimeField(blank=True, null=True)),
                ('application', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='deficiencies', to='applications.application')),
                ('raised_by', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='deficiencies_raised', to=settings.AUTH_USER_MODEL)),
                ('resolved_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='deficiencies_resolved', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'ordering': ['-raised_at'],
            },
        ),
        migrations.CreateModel(
            name='ApplicationFieldDefinition',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('field_code', models.CharField(help_text='Canonical field identifier (e.g. annual_family_income)', max_length=100)),
                ('label', models.CharField(help_text='Display label shown on applicant form', max_length=255)),
                ('description', models.TextField(blank=True, help_text='Guidance text / help message for applicant')),
                ('data_type', models.CharField(choices=[('TEXT', 'Text'), ('NUMBER', 'Number'), ('DATE', 'Date'), ('BOOLEAN', 'Boolean'), ('SELECT', 'Select (Single Choice)'), ('MULTI_SELECT', 'Multi-Select'), ('CURRENCY', 'Currency / Monetary Amount'), ('INSTITUTION', 'Institution / University Identifier'), ('COURSE', 'Course / Academic Program'), ('COUNTRY', 'Country'), ('FILE', 'File / Document Upload'), ('PHONE', 'Phone Number'), ('EMAIL', 'Email Address')], default='TEXT', max_length=50)),
                ('required', models.BooleanField(default=True, help_text='Mandatory field flag')),
                ('applicant_visible', models.BooleanField(default=True)),
                ('officer_visible', models.BooleanField(default=True)),
                ('editable_until_state', models.CharField(default='SUBMITTED', max_length=50)),
                ('validation_schema', models.JSONField(blank=True, default=dict, help_text='JSON schema: min, max, regex, options list, or visibility_condition')),
                ('display_order', models.IntegerField(default=0)),
                ('section', models.CharField(default='GENERAL', help_text='Form section code: PERSONAL, ACADEMIC, ELIGIBILITY, INSTITUTION, etc.', max_length=50)),
                ('source_excerpt', models.TextField(blank=True, help_text='Statutory citation justifying this field requirement')),
                ('status', models.CharField(default='ACTIVE', max_length=30)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('scheme_version', models.ForeignKey(help_text='SchemeVersion governing this field definition', on_delete=django.db.models.deletion.CASCADE, related_name='field_definitions', to='schemes.schemeversion')),
                ('source_document', models.ForeignKey(blank=True, help_text='Official source document establishing this field requirement', null=True, on_delete=django.db.models.deletion.PROTECT, related_name='field_definitions', to='documents.sourcedocument')),
            ],
            options={
                'ordering': ['scheme_version', 'section', 'display_order', 'field_code'],
                'unique_together': {('scheme_version', 'field_code')},
            },
        ),
        migrations.CreateModel(
            name='ApplicationFieldValue',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('value_json', models.JSONField(blank=True, help_text='Structured submitted value', null=True)),
                ('source', models.CharField(choices=[('OFFICER', 'Officer Verified'), ('OFFICIAL_INTEGRATION', 'Official Integration (e.g. DigiLocker)'), ('VERIFIED_DOCUMENT', 'Verified Document Extraction'), ('OCR', 'OCR Extraction'), ('APPLICANT', 'Applicant Declared'), ('SYSTEM', 'System Calculated')], default='APPLICANT', help_text='Source provenance for this value', max_length=50)),
                ('confidence', models.FloatField(default=1.0, help_text='Extraction confidence score (0.0 to 1.0)')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('application', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='field_values', to='applications.application')),
                ('entered_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='entered_field_values', to=settings.AUTH_USER_MODEL)),
                ('field_definition', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='submitted_values', to='applications.applicationfielddefinition')),
            ],
            options={
                'ordering': ['-created_at'],
            },
        ),
        migrations.CreateModel(
            name='EligibilityInputSnapshot',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('payload_json', models.JSONField(default=dict)),
                ('payload_hash', models.CharField(help_text='SHA-256 hash of captured input snapshot', max_length=64)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('evaluation', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='input_snapshot', to='applications.eligibilityevaluation')),
            ],
        ),
    ]
