# Generated by Django 5.1.15 on 2026-09-28 15:39

import django.db.models.deletion
import uuid
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('applications', '0006_applicationdeficiency_applicationfielddefinition_and_more'),
        ('schemes', '0007_schemerule_superseded_at_and_more'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AddField(
            model_name='application',
            name='last_modified_at',
            field=models.DateTimeField(auto_now=True),
        ),
        migrations.AddField(
            model_name='application',
            name='last_modified_by',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='modified_applications', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='application',
            name='revision_number',
            field=models.PositiveIntegerField(default=1, help_text='Optimistic concurrency control revision counter'),
        ),
        migrations.AddField(
            model_name='applicationfieldvalue',
            name='verification_status',
            field=models.CharField(choices=[('UNVERIFIED', 'Unverified'), ('PROVISIONALLY_EXTRACTED', 'Provisionally Extracted'), ('DOCUMENT_VERIFIED', 'Document Verified'), ('OFFICER_VERIFIED', 'Officer Verified'), ('OFFICIAL_VERIFIED', 'Official Verified')], default='UNVERIFIED', help_text='Verification lifecycle status', max_length=50),
        ),
        migrations.AlterField(
            model_name='applicationfieldvalue',
            name='source',
            field=models.CharField(choices=[('OFFICER', 'Officer Verified'), ('OFFICIAL_INTEGRATION', 'Official Integration (e.g. DigiLocker)'), ('VERIFIED_DOCUMENT', 'Verified Document Extraction'), ('APPLICANT', 'Applicant Declared'), ('OCR', 'OCR Extraction (Provisional)'), ('SYSTEM', 'System Calculated')], default='APPLICANT', help_text='Source provenance for this value', max_length=50),
        ),
        migrations.CreateModel(
            name='ApplicationSubmissionSnapshot',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('revision_number', models.PositiveIntegerField()),
                ('submitted_at', models.DateTimeField(auto_now_add=True)),
                ('applicant_data_json', models.JSONField(default=dict)),
                ('form_values_json', models.JSONField(default=dict)),
                ('document_manifest_json', models.JSONField(default=list)),
                ('snapshot_hash', models.CharField(help_text='SHA-256 hash of immutable submission snapshot', max_length=64)),
                ('application', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='submission_snapshots', to='applications.application')),
                ('scheme_version', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='submission_snapshots', to='schemes.schemeversion')),
            ],
            options={
                'ordering': ['-submitted_at'],
            },
        ),
        migrations.CreateModel(
            name='ApplicationUniquenessPolicy',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('max_active_applications', models.PositiveIntegerField(default=1)),
                ('allow_multiple_drafts', models.BooleanField(default=False)),
                ('allow_resubmission', models.BooleanField(default=False)),
                ('duplicate_detection_mode', models.CharField(choices=[('STRICT', 'Strict Rejection'), ('WARN', 'Warning'), ('REVIEW', 'Route to Review')], default='WARN', max_length=30)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('scheme_version', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='uniqueness_policy', to='schemes.schemeversion')),
            ],
        ),
        migrations.CreateModel(
            name='FieldConflict',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('field_code', models.CharField(help_text='Canonical field identifier in conflict', max_length=100)),
                ('values_json', models.JSONField(default=list, help_text='List of contending values observed across sources')),
                ('source_values', models.JSONField(default=dict, help_text='Source-keyed dictionary containing detailed observed values and confidence')),
                ('severity', models.CharField(default='BLOCKING', max_length=30)),
                ('status', models.CharField(choices=[('OPEN', 'Open'), ('UNDER_REVIEW', 'Under Review'), ('RESOLVED', 'Resolved'), ('WAIVED', 'Waived')], default='OPEN', max_length=30)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('resolution', models.TextField(blank=True, help_text='Officer justification and resolution explanation')),
                ('resolved_at', models.DateTimeField(blank=True, null=True)),
                ('application', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='conflicts', to='applications.application')),
                ('resolved_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='resolved_conflicts', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'ordering': ['-created_at'],
            },
        ),
        migrations.CreateModel(
            name='IdempotencyRecord',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('key', models.CharField(db_index=True, max_length=255)),
                ('endpoint', models.CharField(max_length=255)),
                ('request_hash', models.CharField(max_length=64)),
                ('response_status', models.IntegerField()),
                ('response_body', models.JSONField(default=dict)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('expires_at', models.DateTimeField(blank=True, null=True)),
                ('actor', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='idempotency_records', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'indexes': [models.Index(fields=['key', 'actor', 'endpoint'], name='application_key_bb6370_idx')],
                'unique_together': {('key', 'actor', 'endpoint')},
            },
        ),
    ]
