# Generated by Django 5.1.15 on 2026-09-27 16:11

import apps.core.validators
import django.db.models.deletion
import django.utils.timezone
import uuid
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='SourceDocument',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('title', models.CharField(help_text='Official publication title', max_length=255)),
                ('source_type', models.CharField(choices=[('GUIDELINE', 'Guideline'), ('AMENDMENT', 'Amendment'), ('ADVERTISEMENT', 'Advertisement'), ('FAQ', 'FAQ'), ('INSTRUCTION_MANUAL', 'Instruction Manual'), ('SELECTION_CRITERIA', 'Selection Criteria'), ('INSTITUTE_LIST', 'Institute List'), ('RESULT', 'Result'), ('OFFICIAL_WEBPAGE', 'Official Webpage'), ('DATASET', 'Dataset')], help_text='Standard category of the official publication', max_length=50)),
                ('source_url', models.CharField(blank=True, help_text='Publicly accessible official URL (or archived government portal link)', max_length=500)),
                ('academic_year', models.CharField(help_text='Academic cycle, e.g. 2025-26', max_length=20, validators=[apps.core.validators.validate_academic_year])),
                ('document_date', models.DateField(blank=True, help_text='Date of issue/gazette publication', null=True)),
                ('retrieved_at', models.DateTimeField(default=django.utils.timezone.now, help_text='Timestamp when the official document was retrieved and registered')),
                ('checksum', models.CharField(help_text='SHA-256 hash of original document binary', max_length=64, validators=[apps.core.validators.validate_sha256_checksum])),
                ('content_hash', models.CharField(help_text='SHA-256 hash of extracted canonical text/data structure', max_length=64, validators=[apps.core.validators.validate_sha256_checksum])),
                ('status', models.CharField(choices=[('ACTIVE', 'Active'), ('SUPERSEDED', 'Superseded'), ('DEPRECATED', 'Deprecated'), ('VERIFIED', 'Verified Official Publication')], default='VERIFIED', max_length=30)),
                ('notes', models.TextField(blank=True, help_text='Provenance notes, gazette notification number, or legal citations')),
            ],
            options={
                'ordering': ['-retrieved_at'],
            },
        ),
        migrations.CreateModel(
            name='ApplicantDocument',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('document_type', models.CharField(choices=[('CASTE_CERTIFICATE', 'ST Caste/Tribe Certificate'), ('INCOME_CERTIFICATE', 'Competent Authority Income Certificate'), ('ADMISSION_OFFER', 'Admission Offer / Enrolment Letter'), ('FEE_RECEIPT', 'Fee Receipt'), ('DISABILITY_CERTIFICATE', 'UDID / Disability Certificate'), ('PASSPORT', 'Passport (for Overseas Scholarship)'), ('ACADEMIC_TRANSCRIPT', 'Academic Transcript / Marksheet'), ('OTHER', 'Other Supporting Document')], max_length=50)),
                ('file', models.FileField(blank=True, null=True, upload_to='applicant_docs/%Y/%m/')),
                ('file_name', models.CharField(max_length=255)),
                ('checksum', models.CharField(help_text='SHA-256 hash of the uploaded applicant document', max_length=64, validators=[apps.core.validators.validate_sha256_checksum])),
                ('ocr_extracted_text', models.TextField(blank=True)),
                ('ocr_confidence_score', models.FloatField(default=0.0, help_text='Assistive OCR confidence score (0.0 - 1.0)')),
                ('is_verified_by_officer', models.BooleanField(default=False, help_text='Officer sign-off required for final verification')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('applicant', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='uploaded_documents', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'ordering': ['-created_at'],
            },
        ),
    ]
