# Generated by Django 5.1.15 on 2026-09-27 16:11

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('documents', '0001_initial'),
        ('schemes', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='sourcedocument',
            name='scheme',
            field=models.ForeignKey(blank=True, help_text='Associated scheme if specific to a single scheme', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='source_documents', to='schemes.scheme'),
        ),
        migrations.AddField(
            model_name='sourcedocument',
            name='supersedes_source',
            field=models.ForeignKey(blank=True, help_text='Prior document superseded by this publication', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='superseded_by', to='documents.sourcedocument'),
        ),
        migrations.AddIndex(
            model_name='sourcedocument',
            index=models.Index(fields=['academic_year', 'source_type'], name='documents_s_academi_beafd3_idx'),
        ),
        migrations.AddIndex(
            model_name='sourcedocument',
            index=models.Index(fields=['checksum'], name='documents_s_checksu_505499_idx'),
        ),
    ]
