# Generated by Django 5.1.15 on 2026-09-28 04:38

import django.db.models.deletion
import uuid
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('documents', '0002_initial'),
        ('schemes', '0007_schemerule_superseded_at_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='DocumentRequirement',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('document_type', models.CharField(choices=[('CASTE_CERTIFICATE', 'ST Caste/Tribe Certificate'), ('INCOME_CERTIFICATE', 'Competent Authority Income Certificate'), ('ADMISSION_OFFER', 'Admission Offer / Enrolment Letter'), ('FEE_RECEIPT', 'Fee Receipt'), ('DISABILITY_CERTIFICATE', 'UDID / Disability Certificate'), ('PASSPORT', 'Passport (for Overseas Scholarship)'), ('ACADEMIC_TRANSCRIPT', 'Academic Transcript / Marksheet'), ('OTHER', 'Other Supporting Document')], help_text='Required applicant document type', max_length=50)),
                ('required', models.BooleanField(default=True, help_text='True if mandatory for eligibility evaluation')),
                ('validity_policy', models.CharField(choices=[('PERMANENT', 'Permanent Validity (e.g. ST Caste Certificate)'), ('ISSUE_DATE_REQUIRED', 'Valid Issue Date Required'), ('EXPIRY_DATE_REQUIRED', 'Explicit Future Expiry Date Required'), ('ACADEMIC_YEAR_BOUND', 'Bound to Academic Year of Application'), ('FINANCIAL_YEAR_BOUND', 'Bound to Current Financial Year (e.g. Income Certificate)'), ('NO_EXPIRY_RULE_CONFIGURED', 'No Statutory Expiry Rule Configured (Needs Review)')], default='NO_EXPIRY_RULE_CONFIGURED', help_text='Configured validity policy rule', max_length=50)),
                ('verification_required', models.BooleanField(default=True, help_text='True if officer or digital integration verification is strictly required')),
                ('source_excerpt', models.TextField(blank=True, help_text='Exact excerpt from official guidelines defining this requirement')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('scheme_version', models.ForeignKey(help_text='Target SchemeVersion enforcing this requirement', on_delete=django.db.models.deletion.CASCADE, related_name='document_requirements', to='schemes.schemeversion')),
                ('source_document', models.ForeignKey(blank=True, help_text='Official source document establishing this document requirement', null=True, on_delete=django.db.models.deletion.PROTECT, related_name='document_requirements', to='documents.sourcedocument')),
            ],
            options={
                'ordering': ['scheme_version', 'document_type'],
                'unique_together': {('scheme_version', 'document_type')},
            },
        ),
    ]
