# Generated by Django 5.1.15 on 2026-09-28 15:39

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('documents', '0003_documentrequirement'),
    ]

    operations = [
        migrations.AddField(
            model_name='documentrequirement',
            name='acceptable_file_types',
            field=models.JSONField(blank=True, default=list, help_text="Permitted file formats/MIME types, e.g. ['application/pdf', 'image/jpeg', 'image/png']"),
        ),
        migrations.AddField(
            model_name='documentrequirement',
            name='deficiency_code',
            field=models.CharField(blank=True, help_text='Standard deficiency code triggered if missing or invalid', max_length=100),
        ),
        migrations.AddField(
            model_name='documentrequirement',
            name='deficiency_severity',
            field=models.CharField(default='BLOCKING', help_text='Deficiency severity if document requirement fails', max_length=30),
        ),
        migrations.AddField(
            model_name='documentrequirement',
            name='max_size_mb',
            field=models.PositiveIntegerField(default=5, help_text='Maximum allowed upload file size in megabytes'),
        ),
        migrations.AddField(
            model_name='documentrequirement',
            name='when_required',
            field=models.CharField(default='APPLICATION', help_text='Stage at which document is required (e.g. APPLICATION, SCRUTINY, VERIFICATION)', max_length=50),
        ),
    ]
