# Generated by Django 5.1.15 on 2026-09-29 15:12

import apps.core.validators
import django.db.models.deletion
import django.utils.timezone
import uuid
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('applications', '0007_application_last_modified_at_and_more'),
        ('documents', '0004_documentrequirement_acceptable_file_types_and_more'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='DocumentManifest',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('sha256', models.CharField(max_length=64, validators=[apps.core.validators.validate_sha256_checksum])),
                ('size_bytes', models.PositiveBigIntegerField()),
                ('detected_mime_type', models.CharField(max_length=100)),
                ('storage_key', models.CharField(max_length=500)),
                ('scan_status', models.CharField(max_length=30)),
                ('validation_status', models.CharField(max_length=30)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
            ],
            options={
                'ordering': ['-created_at'],
            },
        ),
        migrations.CreateModel(
            name='DocumentProcessingJob',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('job_type', models.CharField(choices=[('SECURITY_SCAN', 'Security Scan'), ('CONTENT_VALIDATION', 'Content Validation'), ('OCR', 'Optical Character Recognition (Deferred)'), ('DOCUMENT_CLASSIFICATION', 'Document Classification'), ('FIELD_EXTRACTION', 'Field Extraction'), ('VERIFICATION', 'Verification')], default='SECURITY_SCAN', max_length=50)),
                ('status', models.CharField(choices=[('PENDING', 'Pending'), ('PROCESSING', 'Processing'), ('COMPLETED', 'Completed'), ('FAILED', 'Failed (Retryable)'), ('PERMANENT_FAILURE', 'Permanent Failure')], default='PENDING', max_length=30)),
                ('attempts', models.PositiveIntegerField(default=0)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('started_at', models.DateTimeField(blank=True, null=True)),
                ('completed_at', models.DateTimeField(blank=True, null=True)),
                ('error_code', models.CharField(blank=True, max_length=100)),
                ('error_message', models.TextField(blank=True)),
                ('correlation_id', models.CharField(blank=True, db_index=True, max_length=100)),
            ],
            options={
                'ordering': ['-created_at'],
            },
        ),
        migrations.CreateModel(
            name='DocumentVersion',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('version_number', models.PositiveIntegerField(default=1)),
                ('storage_key', models.CharField(max_length=500)),
                ('sha256', models.CharField(max_length=64, validators=[apps.core.validators.validate_sha256_checksum])),
                ('file_size_bytes', models.PositiveBigIntegerField(default=0)),
                ('uploaded_at', models.DateTimeField(default=django.utils.timezone.now)),
                ('lifecycle_status', models.CharField(choices=[('INITIATED', 'Initiated'), ('UPLOADING', 'Uploading'), ('UPLOADED', 'Uploaded'), ('QUARANTINED', 'Quarantined'), ('SCANNING', 'Scanning'), ('SAFE', 'Safe'), ('REJECTED', 'Rejected'), ('PROCESSING', 'Processing'), ('PROCESSED', 'Processed'), ('VERIFICATION_PENDING', 'Verification Pending'), ('VERIFIED', 'Verified'), ('REVOKED', 'Revoked')], default='UPLOADED', max_length=30)),
                ('reason', models.TextField(blank=True, help_text='Reason for uploading this replacement version')),
            ],
            options={
                'ordering': ['document', '-version_number'],
            },
        ),
        migrations.AddField(
            model_name='applicantdocument',
            name='application',
            field=models.ForeignKey(blank=True, help_text='Authoritative business application owning this document', null=True, on_delete=django.db.models.deletion.CASCADE, related_name='documents', to='applications.application'),
        ),
        migrations.AddField(
            model_name='applicantdocument',
            name='content_validation_status',
            field=models.CharField(choices=[('PENDING', 'Pending Validation'), ('VALID', 'Content Valid'), ('INVALID', 'Content Invalid / Malformed'), ('ERROR', 'Validation Error')], default='PENDING', max_length=30),
        ),
        migrations.AddField(
            model_name='applicantdocument',
            name='declared_mime_type',
            field=models.CharField(blank=True, max_length=100),
        ),
        migrations.AddField(
            model_name='applicantdocument',
            name='detected_mime_type',
            field=models.CharField(blank=True, max_length=100),
        ),
        migrations.AddField(
            model_name='applicantdocument',
            name='file_size_bytes',
            field=models.PositiveBigIntegerField(default=0),
        ),
        migrations.AddField(
            model_name='applicantdocument',
            name='lifecycle_status',
            field=models.CharField(choices=[('INITIATED', 'Initiated'), ('UPLOADING', 'Uploading'), ('UPLOADED', 'Uploaded'), ('QUARANTINED', 'Quarantined'), ('SCANNING', 'Scanning'), ('SAFE', 'Safe'), ('REJECTED', 'Rejected'), ('PROCESSING', 'Processing'), ('PROCESSED', 'Processed'), ('VERIFICATION_PENDING', 'Verification Pending'), ('VERIFIED', 'Verified'), ('REVOKED', 'Revoked')], default='INITIATED', max_length=30),
        ),
        migrations.AddField(
            model_name='applicantdocument',
            name='malware_scan_status',
            field=models.CharField(choices=[('NOT_SCANNED', 'Not Scanned'), ('SCANNING', 'Scanning'), ('CLEAN', 'Clean'), ('INFECTED', 'Infected'), ('ERROR', 'Scan Error')], default='NOT_SCANNED', max_length=30),
        ),
        migrations.AddField(
            model_name='applicantdocument',
            name='malware_scan_timestamp',
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='applicantdocument',
            name='metadata_json',
            field=models.JSONField(blank=True, default=dict),
        ),
        migrations.AddField(
            model_name='applicantdocument',
            name='original_filename',
            field=models.CharField(blank=True, max_length=255),
        ),
        migrations.AddField(
            model_name='applicantdocument',
            name='processed_at',
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='applicantdocument',
            name='rejection_reason',
            field=models.TextField(blank=True),
        ),
        migrations.AddField(
            model_name='applicantdocument',
            name='revocation_reason',
            field=models.TextField(blank=True),
        ),
        migrations.AddField(
            model_name='applicantdocument',
            name='revoked_at',
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='applicantdocument',
            name='revoked_by',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='revoked_applicant_documents', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='applicantdocument',
            name='sha256',
            field=models.CharField(blank=True, db_index=True, help_text='Authoritative server-computed SHA-256 digest', max_length=64),
        ),
        migrations.AddField(
            model_name='applicantdocument',
            name='storage_key',
            field=models.CharField(blank=True, help_text='Quarantine or Safe storage key', max_length=500),
        ),
        migrations.AddField(
            model_name='applicantdocument',
            name='upload_source',
            field=models.CharField(default='WEB_PORTAL', max_length=50),
        ),
        migrations.AddField(
            model_name='applicantdocument',
            name='uploaded_at',
            field=models.DateTimeField(default=django.utils.timezone.now),
        ),
        migrations.AddField(
            model_name='applicantdocument',
            name='uploaded_by',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='uploaded_by_documents', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AlterField(
            model_name='applicantdocument',
            name='checksum',
            field=models.CharField(blank=True, help_text='SHA-256 hash of the uploaded applicant document', max_length=64, validators=[apps.core.validators.validate_sha256_checksum]),
        ),
        migrations.AlterField(
            model_name='applicantdocument',
            name='file_name',
            field=models.CharField(blank=True, max_length=255),
        ),
        migrations.AddIndex(
            model_name='applicantdocument',
            index=models.Index(fields=['application', 'document_type'], name='documents_a_applica_02739a_idx'),
        ),
        migrations.AddIndex(
            model_name='applicantdocument',
            index=models.Index(fields=['sha256'], name='documents_a_sha256_2bb6fa_idx'),
        ),
        migrations.AddIndex(
            model_name='applicantdocument',
            index=models.Index(fields=['lifecycle_status'], name='documents_a_lifecyc_3e9bfb_idx'),
        ),
        migrations.AddField(
            model_name='documentmanifest',
            name='document',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='manifests', to='documents.applicantdocument'),
        ),
        migrations.AddField(
            model_name='documentprocessingjob',
            name='document',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='processing_jobs', to='documents.applicantdocument'),
        ),
        migrations.AddField(
            model_name='documentversion',
            name='document',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='versions', to='documents.applicantdocument'),
        ),
        migrations.AddField(
            model_name='documentversion',
            name='supersedes_version',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='superseded_by_versions', to='documents.documentversion'),
        ),
        migrations.AddField(
            model_name='documentversion',
            name='uploaded_by',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='uploaded_document_versions', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddIndex(
            model_name='documentprocessingjob',
            index=models.Index(fields=['document', 'job_type', 'status'], name='documents_d_documen_d8490a_idx'),
        ),
        migrations.AddIndex(
            model_name='documentprocessingjob',
            index=models.Index(fields=['correlation_id'], name='documents_d_correla_dce34f_idx'),
        ),
        migrations.AlterUniqueTogether(
            name='documentversion',
            unique_together={('document', 'version_number')},
        ),
    ]
