# Generated by Django 5.1.15 on 2026-09-29 16:33

import django.db.models.deletion
import django.utils.timezone
import uuid
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('documents', '0005_documentmanifest_documentprocessingjob_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='applicantdocument',
            name='lifecycle_status',
            field=models.CharField(choices=[('INITIATED', 'Initiated'), ('UPLOADING', 'Uploading'), ('UPLOADED', 'Uploaded'), ('QUARANTINED', 'Quarantined'), ('SCANNING', 'Scanning'), ('PROMOTION_PENDING', 'Promotion Pending'), ('RECONCILIATION_REQUIRED', 'Reconciliation Required'), ('SAFE', 'Safe'), ('REJECTED', 'Rejected'), ('PROCESSING', 'Processing'), ('PROCESSED', 'Processed'), ('VERIFICATION_PENDING', 'Verification Pending'), ('VERIFIED', 'Verified'), ('REVOKED', 'Revoked')], default='INITIATED', max_length=30),
        ),
        migrations.AlterField(
            model_name='documentversion',
            name='lifecycle_status',
            field=models.CharField(choices=[('INITIATED', 'Initiated'), ('UPLOADING', 'Uploading'), ('UPLOADED', 'Uploaded'), ('QUARANTINED', 'Quarantined'), ('SCANNING', 'Scanning'), ('PROMOTION_PENDING', 'Promotion Pending'), ('RECONCILIATION_REQUIRED', 'Reconciliation Required'), ('SAFE', 'Safe'), ('REJECTED', 'Rejected'), ('PROCESSING', 'Processing'), ('PROCESSED', 'Processed'), ('VERIFICATION_PENDING', 'Verification Pending'), ('VERIFIED', 'Verified'), ('REVOKED', 'Revoked')], default='UPLOADED', max_length=30),
        ),
        migrations.CreateModel(
            name='DocumentJobExecution',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('task_id', models.CharField(db_index=True, max_length=255)),
                ('stage', models.CharField(default='SECURITY_SCAN', max_length=100)),
                ('execution_status', models.CharField(choices=[('STARTED', 'Started'), ('RUNNING', 'Running'), ('COMPLETED', 'Completed'), ('FAILED', 'Failed'), ('CRASHED', 'Crashed'), ('RETRY', 'Scheduled for Retry')], default='STARTED', max_length=50)),
                ('started_at', models.DateTimeField(default=django.utils.timezone.now)),
                ('finished_at', models.DateTimeField(blank=True, null=True)),
                ('worker_id', models.CharField(blank=True, max_length=255)),
                ('correlation_id', models.CharField(blank=True, db_index=True, max_length=100)),
                ('retry_count', models.PositiveIntegerField(default=0)),
                ('details', models.JSONField(blank=True, default=dict)),
                ('document', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='job_executions', to='documents.applicantdocument')),
                ('job', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='executions', to='documents.documentprocessingjob')),
            ],
            options={
                'ordering': ['-started_at'],
                'indexes': [models.Index(fields=['task_id'], name='documents_d_task_id_e0b53e_idx'), models.Index(fields=['document', 'stage'], name='documents_d_documen_4cc8e5_idx'), models.Index(fields=['correlation_id'], name='documents_d_correla_befdff_idx')],
            },
        ),
        migrations.CreateModel(
            name='SecurityQuarantineRecord',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('detection_result', models.TextField(help_text='Detailed malware/threat signature detection message')),
                ('scanner', models.CharField(help_text='Malware scanner engine that flagged the document', max_length=100)),
                ('detected_at', models.DateTimeField(default=django.utils.timezone.now)),
                ('retention_until', models.DateTimeField(help_text='Mandatory retention deadline before statutory deletion')),
                ('deletion_status', models.CharField(choices=[('RETAINED', 'Retained for Security/Forensics Evidence'), ('PENDING_REVIEW', 'Pending Security Officer Review'), ('PURGED', 'Purged in accordance with Statutory Retention Policy')], default='RETAINED', max_length=50)),
                ('deleted_at', models.DateTimeField(blank=True, null=True)),
                ('quarantine_storage_key', models.CharField(blank=True, max_length=500)),
                ('document', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='quarantine_records', to='documents.applicantdocument')),
            ],
            options={
                'ordering': ['-detected_at'],
                'indexes': [models.Index(fields=['document', 'deletion_status'], name='documents_s_documen_a39da9_idx'), models.Index(fields=['retention_until'], name='documents_s_retenti_05b802_idx')],
            },
        ),
    ]
